language: ruby
rvm:
  - 2.1
script:
  - bundle exec jekyll build

deploy:
  provider: s3
  access_key_id: AKIAIZHGJPDQ5PBDEMBQ
  secret_access_key:
    secure: IKXW7Mtf3/hayc8EArmuGj5EuXskAXwTPfLXyleE3tRIDFcVE34pyKdYfxHXMY59dCIx/n3nY5zlRhcoocW7GQz5xCSs9WlDFbtPOHnNIMYaeKapaEAbPVPIfVIz1gC/D5xUHA9CmB4S3J+3p4z3P7Kf/c/zQlPRr52rITXX5HZKok55I1OJUI7j/OYaXo67ndXqJ0aM6ujJPyjt7XwJCn5Xau1Rj7r3wOx7HmfQAmPycui1xrPJxV1dXVufUiCOHAvFsGMCvQpQqZnor7rQDz/0tjqKKoRbpM8LZdbJWG1ox6q8J3Gp8otxPuoPUJShDRXoXmOIyy0LYnY051Iz0oO07pcX706vxL6RtvDDrplZ9uIzOB1H3tswHsimy4LrEYaPj5PViSf9GYDb/LHdKuJZqXHe6khkGtEtijXmpxgz+VOFCmmh/uvurVPvFeHkusNJpnCSBgGpZDQ3mr0cW+7vq998I+ySEROB9fANIcZIpYdtiQ2Se+6st/FowMsrNBlld5lTO3NZ2DRguInqKejqiu30gRT7uSz1HHDjOCWrED6cPaO5/gLevRQtzzK2TvqoviaKlyp75+huey07Hl/BlB/ZOLNbwmg2kITD3QcNMyzHZ5RMZ4QrNxV8DsFPy135/AHlVU3hzWU/y6eRImCe9XYf9hLaQrpNDgAkGAo=
  bucket: ng-img
  skip_cleanup: true
  local-dir: img
  acl: public_read
  on:
    repo: KingFelix/ng-new
    branch: 
      - gh-pages
      - master
after_deploy:
  - ./script/delete-img.sh
